# Generated by Django 2.2.1 on 2019-06-03 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('sport', 'Новости'), ('economics', 'Экономика'), ('science', 'Наука'), ('tech', 'Техника'), ('it', 'IT'), ('none', 'Без категории')], default='none', max_length=20)),
                ('slug', models.SlugField(default=models.CharField(choices=[('sport', 'Новости'), ('economics', 'Экономика'), ('science', 'Наука'), ('tech', 'Техника'), ('it', 'IT'), ('none', 'Без категории')], default='none', max_length=20), max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_to_posts', to='posts.Categories'),
        ),
    ]
