# Generated by Django 2.2.1 on 2019-06-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190603_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(choices=[('news', 'Новости'), ('economics', 'Экономика'), ('science', 'Наука'), ('tech', 'Техника'), ('it', 'IT'), ('none', 'Без категории')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default='none', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_to_posts', to='posts.Categories'),
        ),
    ]
